### ISSUE TITLE
Automate deployment of website / continuous delivery

### ISSUE THREAD

**Issue by augusto-herrmann** [okfn/publicbodies#115]
Whenever new commits are merged to master, if all tests pass, the code should probably be automatically deployed to the production environment.

So far we only have data tests, but once we have some test coverage on the code as well, it should be a step toward having continuous delivery.

**Comment by augusto-herrmann** [comment]
I cannot configure automatic deployment to Heroku from this repository. The `okfn` organisation does not appear among the options available to select, even after I've authorized Heroku on Github's OAuth:

![heroku-deploy](https://user-images.githubusercontent.com/1058414/132138397-42972cfe-198e-471b-b9af-374853da0a25.gif)

I think the reason is probably because I'm not a *member* of the `okfn` organisation, but rather an *outside collaborator*:

![outside-collaborator](https://user-images.githubusercontent.com/1058414/132138558-8259ce34-cacb-47e8-a324-46bcc1862e9a.gif)

@rufuspollock or @todrobbins can you help?

**Comment by todrobbins** [comment]
@augusto-herrmann I think you're right that it has to do with OKFN membership. Unfortunately, I'm only a member and cannot add you.

**Comment by augusto-herrmann** [comment]
Thanks @todrobbins for looking it up. So unless you have time to set up the deployment of this repo yourself, I guess we're going to have to wait until @rufuspollock can add me as a member.

**Comment by todrobbins** [comment]
![Screen Shot 2021-09-08 at 11 30 24 AM](https://user-images.githubusercontent.com/158590/132556787-9bb635c3-881c-4879-9d7a-7170fa305b64.png)

I connected the repo and enabled automatic deployment and also just kicked off a manual deploy.

**Comment by augusto-herrmann** [comment]
Yay, thank you @todrobbins! :tada: 

Now I can finally try to merge PR #111. Once it is merged, though, I'm not sure if deployment to Heroku will happen via their direct Node.js support or building a Docker container, so I still may need to make some adjustments in Heroku. Let's hope my permissions are enough to do it.
