### ISSUE TITLE
Prepare the publicbodies.org ODD 2022 Sprint

### ISSUE THREAD

**Issue by augusto-herrmann** [okfn/publicbodies#138]
The [Open Data Day](https://opendataday.org) 2022 is only a few days from now and it would be nice to do a sprint for publicbodies.org. For that, we need to prepare a few things:

* [x] choose a messaging tool for organizing the event (we're using the Matrix channel [#publicbodies.org:matrix.org](https://matrix.to/#/#publicbodies.org:matrix.org))
* [ ] agree upon a schedule (there are people interested in it from many different time zones)
* [ ] prioritize and pick which issues we will work on
 * candidate issues and possibilities:
   * data validation: #135;
   * reorganize data structure, as suggested by @mattiasaxell (issues with label "[Data model](https://github.com/okfn/publicbodies/issues?q=is%3Aopen+is%3Aissue+label%3A%22Data+model%22)")
   * automatic data updates from sources, e.g. #15, #18, #59, #81, #116;
   * new UI and/or frontend (as suggested by @nikeshbalami in chat)
* [x] choose the tool set for the video call (and possibly streaming / recording)
* [x] choose a messaging tool for participants (possibly the same Matrix channel?)
* [ ] add the event to the map on opendataday.org website (where, considering there isn't a single physical location?)

If you'd like to help, just reply to this thread or use the chat on [#publicbodies.org:matrix.org](https://matrix.to/#/#publicbodies.org:matrix.org) channel on Matrix.

**Comment by augusto-herrmann** [comment]
Since not even one person expressed interest in participating in this proposed activity, I'm now cancelling the proposed Open Data Day workshop.

**Comment by mattiasaxell** [comment]
@augusto-herrmann Can it maybe work if we make a RSVP-link with dates that are 1-2 months ahead? Or if we join to discuss the issue at a Friday coffee break with govdirectory.org? Link and info: https://www.wikidata.org/wiki/Wikidata:WikiProject_Govdirectory/Events

I see MySociety, Alaveteli network, OK network, Wikidata and GovDirectory as relevant actors to be invited. Perhaps also groups from https://www.w3.org/community/groups/ like https://www.w3.org/community/opengov/ which latest post is about this issue: https://www.w3.org/community/opengov/2016/02/21/core-public-organisation-vocabulary/

**Comment by morisy** [comment]
I'd also be interested in scheduling out for a future date! my username at gmail is best email.

**Comment by augusto-herrmann** [comment]
Actually, we did do an [activity](https://github.com/augusto-herrmann/opendataday-publicbodies-nepal/) planned in the last minute on the Open Data Day with Open Knowledge Nepal, thanks to @nikeshbalami.

@mattiasaxell, great idea! Are you already in contact with some of these groups? Would you be willing to arrange this with them?

@morisy, how about we discuss this in the Matrix chat [#publicbodies.org:matrix.org](https://matrix.to/#/#publicbodies.org:matrix.org)? That way everyone can participate in the discussions.

**Comment by mattiasaxell** [comment]
Great! I saw some activity! 

@augusto-herrmann Yes I am. I will send out a Framadate link to all of you to book a date and time for a meeting. Will try to think of what can work in terms of meeting time for Brazil, U.S., England, Sweden.

@morisy You're more than welcome to join the chat!

**Comment by dpriskorn** [comment]
What time zone is it?

**Comment by salgo60** [comment]
> What time zone is it?

[CET](https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/event/webinar-dedicated-review-core-vocabularies-27th-october-1030-cet)

**Comment by dpriskorn** [comment]
> > What time zone is it?
> 
> @dpriskorn 
> 
> 
> 
> [CET link event](https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/event/webinar-dedicated-review-core-vocabularies-27th-october-1030-cet) 
> 
> * [GITHUB Semantic Interoperability Community](https://github.com/SEMICeu)

Planerar delta 😀

**Comment by salgo60** [comment]
Do they know the WD work that is done
* [Wikidata:WikiProject_Country_subdivision/Items](https://www.wikidata.org/wiki/Wikidata:WikiProject_Country_subdivision/Items)
* [Wikidata:WikiProject every politician](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician)

**Comment by augusto-herrmann** [comment]
Thanks for the heads up, @mattiasaxell.

I also received an invitation by email. Unfortunately, it was on too short notice (less than 24 hours) and I already had other commitments at the day. The lack of time zone information was also confusing – I only saw the answers in this thread after the event.

Can anyone who participated comment on how the work group meeting was?

**Comment by dpriskorn** [comment]
> Thanks for the heads up, @mattiasaxell.
> 
> 
> 
> I also received an invitation by email. Unfortunately, it was on too short notice (less than 24 hours) and I already had other commitments at the day. The lack of time zone information was also confusing – I only saw the answers in this thread after the event.
> 
> 
> 
> Can anyone who participated comment on how the work group meeting was?

It was my first time in that type of meeting. They talked a lot about fine details in the RDF data model. 
I found the whole thing quite pointless since instead of reinventing the wheel they could just link to a Wikibase or Wikidata where the information is stored. 
OSM and Wikidata already solved all the issues they seem to have in their model 🤷‍♂️
These days having an ontology outside of a Wikibase installation seems like intentionally poking yourself in the eye with a stick to me at least. 
I have seen a lot of garbage ontologies during my time as volunteer. For example in the librisxl system from the national library of Sweden.
I tried pinpointing the identity of the most active participants and added two of them to Wikidata. 
One of them had written an interesting paper that I found interesting. I can post links if anyone is interested.

**Comment by salgo60** [comment]
> I found the whole thing quite pointless

@dpriskorn  I agree I see a #Linkeddata anti pattern that we have people just speaking about RDF and nothing gets delivered
* **good patterna I have see**
  * WIkidata was done **2012 with a small very skilled team with a focus on deliver**
     * done fast - [start 1 april 2012. delivered oct 2012](https://www.linkedin.com/pulse/wikidata-turns-10-denny-vrande%25C4%258Di%25C4%2587)
     * based on the [RENDER](http://render-project.eu/) project -->  [The goal of this project is to explore and support the diversity of knowledge on the Web](https://blog.wikimedia.de/2013/06/04/on-truths-and-lies/)
     * follow the **patterns of Wikipedia** with versions history, subscription, easy to discuss things, trust that users have good intentions and that user themself is a self regulating that will deliver good data....
