### ISSUE TITLE
Fix infinite redirect and get site back online

### ISSUE THREAD

**Issue by augusto-herrmann** [okfn/publicbodies#151]
Right now when accessing the site the user gets infinite redirects, which make it inaccessible.

![publicbodies-org-error](https://user-images.githubusercontent.com/1058414/163247650-eb72bcf5-b152-4fec-86de-b7ec94a6bf15.png)

We should fix the site deployment ASAP.

Judging by the headers it could be some kind of problem with CloudFlare.

**Comment by todrobbins** [comment]
Could be... Do you have Heroku access now? Also, could be a DNS issue maybe?

**Comment by augusto-herrmann** [comment]
No, Heroku has changed its terms of use recently and I've decided to delete my account because of that.

I have already started working on converting the site to a statically generated Jekyll site (issue #154 on branch [jekyll-site](https://github.com/okfn/publicbodies/tree/jekyll-site)) so we can host it on Github Pages instead.

Once it is done we will still need to change the DNS to point it to Github Pages.

**Comment by todrobbins** [comment]
Sounds good! I'll take a look at the new branch. DNS changes will need to come from @loleg

**Comment by augusto-herrmann** [comment]
Hi @amercader!

With PR #158 we're ready to move on to Github Pages. I think we should change the DNS already, the site on Heroku has been offline for a few months anyway.

**Comment by augusto-herrmann** [comment]
In addition to the DNS change, to make Github Pages work someone would need to configure it in the "Settings" tab of this repository, which I do not have access to.

**Comment by amercader** [comment]
@augusto-herrmann you should be an admin for this repo now
I've updated the DNS to point to Github pages

**Comment by augusto-herrmann** [comment]
Thanks, @amercader!

I'm in a hurry right now but should work in getting the site back online as soon as I can.
