### ISSUE TITLE
Add to repository all scripts that load publicly avaliable data

### ISSUE THREAD

**Issue by augusto-herrmann** [okfn/publicbodies#60]
We should create "scripts/import/XX" directories as needed in the repository to hold scripts to update the data, where avaliable from public sources. That way it would be much easier to keep the data up-to-date.

**Comment by augusto-herrmann** [comment]
[Tuttle](https://discuss.okfn.org/t/a-tool-for-collaborating-on-datapackages/1397) is also one to consider.

**Comment by rgrp** [comment]
@augusto-herrmann personally i would keep this super simple and just put scripts in the scripts directory with a README on how to run them ;-)

**Comment by augusto-herrmann** [comment]
I'm closing this old issue as solved, because current data sources that have import scripts are already present at the [import/scripts](https://github.com/okfn/publicbodies/tree/master/scripts/import) folder.
