### ISSUE TITLE
implement new import scripts to update Brazilian data

### ISSUE THREAD

**Issue by augusto-herrmann** [okfn/publicbodies#72]
The Brazilian dataset is quite outdated. Especially as a recent organizational reform changed a lot of Ministries.

The source dataset has changed a lot too. Used to be a big XML dump (this is what the [import scripts](https://github.com/okfn/publicbodies/tree/master/scripts/import/br) used to read), but now it's a [RESTful API](http://dados.gov.br/dataset/siorg) using JSON. The data model and fields available have also changed. So the scripts need to be completely re-done.

**Comment by todrobbins** [comment]
@augusto-herrmann are you interested in taking this or should I move forward with this script?

**Comment by augusto-herrmann** [comment]
Sure, but @todrobbins before I work in this, I'd like to confirm whether or not you actually did any work in it already, considering a couple of months have passed since then.

**Comment by rufuspollock** [comment]
@augusto-herrmann i don't believe @todrobbins has done any specific work here so please go ahead!

**Comment by todrobbins** [comment]
@rufuspollock is correct as I have not done any work in this area. Carry on!

**Comment by augusto-herrmann** [comment]
I am having difficulty with this as I am unsure about how to handle the changes in organizational structures and how to map identifiers between versions of the organizational structure. I think we need to solve issue #68 before properly handling this.

Alternatively, I could just naïvely run the scripts to obtain the latest version without caring about keeping the ids consistent between the version in use in publicbodies.org (which is _quite old_) and the current organizational structure of the Brazilian government. Of course, if there is something that currently depends on those ids, it would most likely be broken by this approach.

**Comment by rufuspollock** [comment]
@augusto-herrmann i've commented in #68. do you want to try something like that here?

**Comment by augusto-herrmann** [comment]
> @augusto-herrmann i've commented in #68. We could trial out the solution of #68 here and see how it goes ...

I did not handle or track in time the changes to the structure of public bodies in this PR. There are too many changes over so many years, that it would take an "epic" effort to be able to do that. I don't even think that the structure at a certain point in time is available as open data, so that would be difficult to obtain if not outright impossible.

For now, we just replace the file with the current structure of public bodies in Brazil. Not even the ids are necessarily consistent with the old data, as a different algorithm was used now to generate the slugs (we now use the `python-slugify` package, while it was a custom slug making code before – I don't think even this lib existed at the time).
